[tool.ruff]
# Enable pycodestyle (`E`), Pyflakes (`F`), and isort (`I`) codes
select = ["E", "F", "I", "W", "C90", "UP", "B", "A", "COM", "C4", "DTZ", "T10", "EM", "EXE", "FA", "ICN", "INP", "ISC", "G", "ICN", "Q", "RSE", "RET", "SLF", "SLOT", "SIM", "TID", "TCH", "ARG", "PIE", "PYI", "PT", "LOG", "RED", "FURB", "ERA", "PD", "PGH", "PL", "TRY", "FLY", "PERF", "FBT", "CLE", "T20", "NPY", "AIR", "S", "BLE", "FIX", "YTT", "BAB", "DJ", "RUF"]

# Same as Black.
line-length = 88

# Assume Python 3.8+
target-version = "py38"

[tool.ruff.lint]
# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.lint.isort]
known-first-party = ["bot", "my_utils", "website"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
"tests/**/*" = ["S101", "PLR2004"]
"bot/test.py" = ["F401", "E501"]
"bot/test_mention_bot.py" = ["F401", "E501"]

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto" 